//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace Diagram
{
    
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<User> UserSet { get; set; }
        public virtual DbSet<Producer> ProducerSet { get; set; }
        public virtual DbSet<Consumer> ConsumerSet { get; set; }
        public virtual DbSet<Finca> FincaSet { get; set; }
        public virtual DbSet<Favorite> FavoriteSet { get; set; }
        public virtual DbSet<Product> ProductSet { get; set; }
        public virtual DbSet<Category> CategorySet { get; set; }
        public virtual DbSet<Review> ReviewSet { get; set; }
        public virtual DbSet<ProducerProduct> ProducerProductSet { get; set; }
        public virtual DbSet<Order> OrderSet { get; set; }
        public virtual DbSet<DetailOrder> DetailOrderSet { get; set; }
        public virtual DbSet<Module> ModuleSet { get; set; }
        public virtual DbSet<Form> FormSet { get; set; }
        public virtual DbSet<Rol> RolSet { get; set; }
        public virtual DbSet<Permission> PermissionSet { get; set; }
        public virtual DbSet<FormModule> FormModuleSet { get; set; }
        public virtual DbSet<RolFormPermission> RolFormPermissionSet { get; set; }
        public virtual DbSet<RolUser> RolUserSet { get; set; }
        public virtual DbSet<Person> PersonSet { get; set; }
    }
}
