//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolFormPermission
    {
        public int Id { get; set; }
        public int FormId { get; set; }
        public int PermissionId { get; set; }
        public int RolId { get; set; }
    
        public virtual Form Form { get; set; }
        public virtual Permission Permission { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
